version: '3'

services:
  php:
    container_name: php
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_MAXNESTING_LEVEL: 1000
      XDEBUG_REMOTE_CONNECT_BACK: 1
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - '9000:9000'
      - '8085:8085'
    volumes:
      - ./:/var/www/application:delegated
      # temp
      - ../orolyn/:/var/www/orolyn:delegated
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/application:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

